### PR TITLE
Enable bitcode

### PR DESCRIPTION
**Pull request by raxcat**
Hi,

I add a flag that would ask compiler to enable bit code. And tested with 
- IDZPrecompiledOgg
  - No issue
- IDZPrecompiledFlag
  - No issue: obj-c framework
  - libFlac++ build error

I have no idea why libFlac++ fails. But both iOS frameworks does work. 

If anyone is looking for bitcode support. This is it.

### CODE REVIEW

**Comment by iosdevzone** [comment]
Thanks for the pull request. I really dropped the ball on this one (enabling bitcode). I'll take a look at libFLAC++ and see if I can figure out why it's failing. As soon as I do I'll merge this.

**Comment by raxcat** [comment]
No hurry. I am grateful.  👍

**Comment by raxcat** [comment]
👍  will try it in few days

**Comment by iosdevzone** [comment]
Still doing some final testing. Will package up a precompiled release as well as soon as I am confident. Sorry for the delay on this. Thanks for your patience.

**Comment by raxcat** [comment]
Sure, no problem. Really appreciate your help.

**Pull request merged**
